config/routes.rb
UStagram::Application.routes.draw do
  devise_for :users
  root "grams#index"

  resources :grams do
    resources :comments, only: :create
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :gram
  belongs_to :user
end

app/models/gram.rb
class Gram < ActiveRecord::Base
  validates :message, presence: true
  validates :picture, presence: true
  has_many :comments
  
  mount_uploader :picture, PictureUploader

  belongs_to :user

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :grams
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def render_not_found(status=:not_found)
   render text: "#{status.to_s.titleize} :(", status: status
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @gram = Gram.find_by_id(params[:gram_id])
    return render_not_found if @gram.blank?

    @gram.comments.create(comment_params.merge(user: current_user))
    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:message)
  end

end

app/controllers/grams_controller.rb
class GramsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @grams = Gram.all
  end

  def new
    @gram = Gram.new
  end

  def create
    @gram = current_user.grams.create(gram_params)

    if @gram.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
  end

  def edit
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) if @gram.user != current_user
  end

  def update
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) if @gram.user != current_user

    @gram.update_attributes(gram_params)
    if @gram.valid?
      redirect_to root_path
    else
      return render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @gram = Gram.find_by_id(params[:id])
    return render_not_found if @gram.blank?
    return render_not_found(:forbidden) if @gram.user != current_user
    @gram.destroy
    redirect_to root_path
  end


  private

  def gram_params
    params.require(:gram).permit(:message, :picture)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/grams_helper.rb
module GramsHelper
end

app/views/grams/edit.html.erb
<div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3 form card">


  <h2>Edit Page</h2>

  <%= simple_form_for @gram do |f| %>
  <%= f.input :message %>
  <%= f.input :picture %>
  <%= f.submit 'Update', class: 'my-btn' %>
  <% end %>

</div>

app/views/grams/index.html.erb
<div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
  <% @grams.each do |gram| %>
  <div class="card">
    <div class="handle">
      <%= gram.user.email %>
      </div>
      <%= image_tag gram.picture, class: "img-responsive" %>
      <p><%= gram.message %></p>
      <div class="gram-actions pull-right">
        <% if current_user && current_user == gram.user %>
          <%= link_to 'Edit', edit_gram_path(gram) %>
          <%= link_to 'Delete', gram_path(gram), method: :delete, data: {confirm: 'Are you sure?'} %>
        <% end %>
      </div>
      <br class="clear-fix">

      <div class="comments">
        <h3>Comments</h3>

        <% gram.comments.each do |comment| %>
          <div class="comment">
            <span class="comment_handle">
              <%= comment.user.email %>
            </span>

            <%= comment.message %>
          </div>
        <% end %>

        <h4>Add a comment</h4>
        <%= simple_form_for Comment.new, url: gram_comments_path(gram) do |f| %>
        <%= f.input :message %>
        <%= f.submit 'Add Comment', class: 'my-btn' %>
        <% end %>
      </div>
  </div>
  <% end %>
</div>
<br>
<br>

app/views/grams/new.html.erb
<div class="col-xs-10 col-xs-offset-1 col-sm-8 col-sm-offset-1 col-md-6 col-md-offset-3 card form">
  <h1>New Gram</h1>
  <%= simple_form_for @gram do |g| %>
  <%= g.input :picture %>
    <%= g.input :message %>
    <br />
    <%= g.submit "Post", class: "my-btn" %>

  <% end %>
</div>

app/views/grams/show.html.erb
<div class="container">
  <h2>Show Page</h2>
  <%= @gram.inspect %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>uStagram</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>


  <nav class="navbar navbar-default">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display and Desktop -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="brand" href="/">uStagram</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

      <% if (!user_signed_in?) %>
      <li><%= link_to 'Sign Up', new_user_registration_path %></li>
      <li><%= link_to 'Sign In', new_user_session_path %></li>
      <% else %>


      </ul>


      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= current_user.email %><span class="caret"></span></a>

          <ul class="dropdown-menu">
            <li><a href="#">Summary</a></li>
            <li><a href="#">Account Settings</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
          </ul>

        </li>

      <% end %>

        </ul>
    </div><!-- /.navbar-collapse -->
  </nav>


  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>